apiVersion: networking.k8s.io/v1  #extensions/v1beta1 #v0.47.x #networking.k8s.io/v1 #extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    #- host: ticketing.dev
  - http:
      paths:
      - path: /api/payments/?(.*)
        pathType:
        backend:
          service:
            name: payments-srv
            port:
              number: 3000
          #serviceName: payments-srv
          #servicePort: 3000
      - path: /api/users/?(.*)
        pathType:
        backend:
          service:
            name: auth-srv
            port:
              number: 3000
      - path: /api/tickets/?(.*)
        pathType:
        backend:
          service:
            name: tickets-srv
            port:
              number: 3000
      - path: /api/orders/?(.*)
        pathType:
        backend:
          service:
            name: orders-srv
            port:
              number: 3000
      - path: /?(.*)
        pathType:
        backend:
          service:
            name: client-srv
            port:
              number: 3000